export const generate_template = (config, data) => `
# What's New?

All notable updates to this project will be documented in this file.

${data
  .map(
    (d) => `
### ${d.group}

${d.commits
  .map(
    (
      c,
    ) => `- [\`${c.hash}\`](https://www.github.com/${config.gh}/commit/${c.hash}) — **${c.type}** ${c.message} by **${c.username}**
`,
  )
  .join("")}

`,
  )
  .join("")}

―  
Generated by [Braudel](https://www.github.com/charnould/braudel)`;
